language: python

python:
  - "3.7"

env:
  - TRAVIS=1

services:
  - docker
  - mongodb

cache: pip

install:
  - pip3 install -r src/requirements.txt
  - cp config/environment.env.example config/environment.env
  - export $(egrep -v '^#' config/environment.env | xargs)
  - export MONGO_HOST=127.0.0.1

before_script:
  - sleep 15

script:
  - coverage run -m pytest src/

after_script:
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
